name: app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  get: ^4.6.1
  flutter_lints: ^1.0.0
  google_fonts: ^2.3.1
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^7.8.0
  intl_phone_field: ^3.1.0
  percent_indicator: ^4.0.0


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
  fonts:
    - family: Mark-Pro     
      fonts:
        - asset: assets/fonts/mark-pro.ttf